- hosts: localhost
  tasks:
    - name: Check for homebrew
      stat: 
        path: /opt/homebrew/bin/brew
      register: brew_dir

    - name: Install homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      become: true
      when: not brew_dir.stat.exists

    - name: Install iTerm
      homebrew_cask: name=iterm2

    - name: Install neovim
      homebrew: name=neovim
      tags:
       - new

    - name: Install Stow
      homebrew: name=stow

    - name: Install volta
      homebrew: name=volta

    - name: set default git config user name
      git_config:
        name: user.name
        scope: global
        value: 'Stefan Trost'

    - name: set default git config user email
      git_config:
        name: user.email
        scope: global
        value: 'stefan@techscene.de'

    - name: Check if ohmyzsh is installed
      stat:
        path: "~/.oh-my-zsh/"
      register: ohmyzsh_dir

    - name: install oh my zsh
      shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
      when: not ohmyzsh_dir.stat.exists

    - name: install ohmyzsh Spaceship Theme
      homebrew: name=spaceship

    - name: Symlink Spaceship Theme
      shell: ln -sF $(brew --prefix)/opt/spaceship/spaceship.zsh-theme ~/.oh-my-zsh/custom/themes/spaceship.zsh-theme

    - name: Install ZSH Autosuggestions
      homebrew: name=zsh-autosuggestions

    - name: Symlink ZSH Autosuggestions
      shell: ln -sF $(brew --prefix)/opt/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Check if dotfiles exist
      stat:
        path: ~/.dotfiles
      register: dots

    - name: Clone dotfiles
      git:
        repo: git@github.com:stefantrost/.dotfiles.git
        dest: ~/.dotfiles
      when: not dots.stat.exists

    - name: Run stow
      shell: "stow . --target {{ ansible_env.HOME }}"
      args:
        chdir: ~/.dotfiles
      register: result
      changed_when: 'result.stderr is search("Link: ")'

    - name: Install fzf
      homebrew: name=fzf

    - name: Install Ripgrep
      homebrew: name=ripgrep

    - name: Install tmux
      homebrew: name=tmux

    - name: Install/clone TPM
      git:
        repo: https://github.com/tmux-plugins/tpm 
        dest: ~/.tmux/plugins/tpm

    - name: Tap arl for gitmux
      homebrew_tap: 
        name: arl/arl

    - name: Install gitmux
      homebrew: name=gitmux

    - name: Source tmux conf
      shell: tmux source ~/.tmux.conf

    - name: Check if Intergast project exists
      stat:
        path: ~/Projects/work/intergast
      register: intergast

    - name: Clone Intergast Project
      git:
        repo: git@bitbucket.org:intergastonline/backend.git
        dest: ~/Projects/work/intergast
        accept_hostkey: yes
      when: not intergast.stat.exists

    - name: Check if Epic Points project exists
      stat:
        path: ~/Projects/work/epic-points
      register: epicpoints

    - name: Clone Epic Points Project
      git:
        repo: git@github.com:techscene/epic-points.git
        dest: ~/Projects/work/epic-points
        accept_hostkey: yes
      when: not epicpoints.stat.exists

    - name: Set Git config Intergast
      git_config:
        name: user.email
        scope: local
        repo: ~/Projects/work/intergast/
        value: 's.trost@qubix.de'

    - name: Install Fira Code Font
      homebrew_cask: 
        name: font-fira-code-nerd-font
      tags: 
        - font

    - name: Install Docker
      homebrew_cask: name=docker

    - name: Install Arc Browser
      homebrew_cask: name=arc

    - name: Install Chrome Browser
      homebrew_cask: name=google-chrome

    - name: Install Firefox Browser
      homebrew_cask: name=firefox

    - name: Install Spotify
      homebrew_cask: name=spotify

    - name: Install Teams
      homebrew_cask: name=microsoft-teams

    - name: Install OpenVPN Connect
      homebrew_cask: name=openvpn-connect

    - name: Install VLC
      homebrew_cask: name=vlc

    - name: Install Handbrake
      homebrew_cask: name=handbrake
      
    - name: Install go
      homebrew: name=go

    - name: Source .zshrc
      shell: source ~/.zshrc
      ignore_errors: true

    - name: Install AppStore apps 1Password, Clean My Mac, Magnet, XCode, HP Smart
      mas: 
        id:
          - 441258766
          - 1339170533
          - 497799835
          - 1474276998
          - 1333542190
        state: present
        upgrade_all: true

    - name: Output next steps
      shell: "echo 'Set Fira Code Nerd Font as iTerm font and press prefix+I in tmux to download plugins'"


